// Scans public/patel-bakery and writes src/assets.generated.ts so the film
// automatically picks up any photos, logo, font or audio you drop in.
// Runs automatically before `npm run studio` / `npm run render`.
import {readdirSync, statSync, writeFileSync} from 'node:fs';
import {join, relative, sep} from 'node:path';

const root = join(process.cwd(), 'public');
const base = join(root, 'patel-bakery');
const MEDIA = /\.(png|jpe?g|webp|avif|gif|svg|mp4|webm|mov|mp3|wav|m4a|aac|ogg|woff2?|otf|ttf)$/i;

const walk = (dir) =>
  readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) return name === 'fallback' ? [] : walk(p);
    return MEDIA.test(name) ? [relative(root, p).split(sep).join('/')] : [];
  });

const files = walk(base).sort();
writeFileSync(
  join(process.cwd(), 'src', 'assets.generated.ts'),
  `// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.\n` +
    `export const AVAILABLE_ASSETS: readonly string[] = ${JSON.stringify(files, null, 2)};\n`,
);
console.log(`[assets] ${files.length} brand asset(s) found in public/patel-bakery`);
for (const f of files) console.log('  •', f);
