// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.
export const AVAILABLE_ASSETS: readonly string[] = [
  "patel-bakery/audio/crust-crackle.wav",
  "patel-bakery/audio/dough.wav",
  "patel-bakery/audio/final-impact.wav",
  "patel-bakery/audio/flour.wav",
  "patel-bakery/audio/logo-reveal.wav",
  "patel-bakery/audio/logo-riser.wav",
  "patel-bakery/audio/music.wav",
  "patel-bakery/audio/oven-ambience.wav",
  "patel-bakery/audio/oven-door.wav",
  "patel-bakery/audio/packaging.wav",
  "patel-bakery/audio/paper.wav",
  "patel-bakery/audio/whoosh.wav",
  "patel-bakery/logo/emblem-brown.svg",
  "patel-bakery/logo/emblem-gold.svg",
  "patel-bakery/logo/emblem-white.svg",
  "patel-bakery/logo/logo-brown.svg",
  "patel-bakery/logo/logo-cream.svg",
  "patel-bakery/logo/logo-gold.svg",
  "patel-bakery/logo/logo-white.svg"
];
